// Render /vaults from a snapshot directory: the four public aggregates and provenance. No rows, no ladder.
import fs from "node:fs"; import path from "node:path";
const dir = process.argv[2], out = process.argv[3] || "site-out"; if (!dir) throw new Error("usage: render <snapshotDir> [outDir]");
const J = (n) => JSON.parse(fs.readFileSync(path.join(dir, n), "utf8")); const m = J("manifest.json"), mt = J("month-tier.json"), mu = J("matured-unredeemed.json"), fl = J("flows.json"), tot = J("totals.json"); const sums = fs.readFileSync(path.join(dir, "SHA256SUMS"), "utf8");
const esc = (s) => String(s).replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c])); const usd = (c) => "$" + (c / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }); const dgb = (s) => (s / 1e8).toLocaleString(undefined, { maximumFractionDigits: 0 }) + " DGB"; const date = (t) => new Date(t * 1000).toISOString().replace("T", " ").slice(0, 16) + " UTC";
const gate = m.exact_gate ? (m.exact_gate.supply_cents_match && m.exact_gate.collateral_sats_match && m.exact_gate.open_count_match ? "three RPC fields match at this height" : "RPC mismatch — see manifest") : "RPC comparison not available at this height (node RPC unresponsive)";
const jsonld = { "@context": "https://schema.org", "@type": "Dataset", name: "DigiDollar collateral positions — public aggregates", description: "Maturity by month and tier, matured-but-unredeemed totals with age buckets, daily mint/close/burn flows, and status totals for DigiDollar positions on DigiByte mainnet, as of a settled snapshot height. Chain-only status; no per-position data.", url: "https://dgbinsights.com/vaults/", license: "https://opensource.org/licenses/MIT", isAccessibleForFree: true, creator: { "@type": "Organization", name: "dgb-tools", url: "https://github.com/dgb-tools/dd-position-scanner" }, version: m.snapshot_id, distribution: m.files.map((f) => ({ "@type": "DataDownload", encodingFormat: "application/json", contentUrl: `https://dgbinsights.com/vaults/snapshots/${m.snapshot_id}/${f}` })) };
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>DigiDollar collateral positions — dgbinsights</title><meta name="description" content="How much DigiDollar collateral is locked, when it can leave, and how much has matured without being redeemed — public aggregates from every position on DigiByte mainnet, chain-only status, no per-position data."><link rel="canonical" href="https://dgbinsights.com/vaults/"><script type="application/ld+json">${JSON.stringify(jsonld)}</script>
<style>body{font:15px/1.5 system-ui,sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem;color:#111}table{border-collapse:collapse;font-variant-numeric:tabular-nums}td,th{border-bottom:1px solid #e5e5e5;padding:.3rem .6rem;text-align:right}th:first-child,td:first-child{text-align:left}.note{background:#fff7ed;border-left:4px solid #b45309;padding:.6rem 1rem}code{font-size:.9em}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:.6rem}.k{border:1px solid #e5e5e5;padding:.6rem;border-radius:6px}.k b{display:block;font-size:1.4em}</style></head><body>
<p><a href="/">dgbinsights</a> · <a href="/lookup">lookup</a> · <a href="/oracles/">oracles</a> · <a href="/mainnet-report">mainnet report</a></p>
<h1>DigiDollar collateral positions</h1>
<p class="note"><strong>Preview.</strong> ${esc(m.label)}; ${esc(gate)}. Snapshot <code>${m.snapshot_id}</code> as of block ${m.snapshot_end_height.toLocaleString()} (${date(m.snapshot_end_time)}). Status is chain-only: <em>chain-matured, unspent</em> means the lock height has passed and the collateral is unspent — it does not mean the owner can redeem (that also needs the owner's key, the required DD burn, and no freeze). Read the <a href="https://github.com/dgb-tools/dd-position-scanner/blob/main/METHODOLOGY.md">methodology</a>. No per-position data is published.</p>
<div class="grid"><div class="k"><b>${tot.locked + tot.chain_matured_unspent}</b>open positions (${tot.locked} locked, ${tot.chain_matured_unspent} chain-matured, unspent)</div><div class="k"><b>${usd(tot.outstanding_supply_cents)}</b>DD outstanding from open positions</div><div class="k"><b>${dgb(tot.unspent_collateral_sats)}</b>collateral unspent</div><div class="k"><b>${usd(mu.cents)}</b>matured but unredeemed (${mu.positions} positions, ${dgb(mu.collateral_sats)})</div></div>
<h2>Matured but unredeemed, by age since maturity</h2><p>The number the Integrator's Guide says nobody publishes: collateral whose lock has passed and which no one has released. It sits inside every backing figure while being unavailable to holders.</p>
<table><thead><tr><th>age since maturity</th><th>positions</th><th>DD</th><th>collateral</th></tr></thead><tbody>${Object.entries(mu.age_buckets).map(([b, v]) => `<tr><td>${b}</td><td>${v.positions}</td><td>${usd(v.cents)}</td><td>${dgb(v.collateral_sats)}</td></tr>`).join("")}</tbody></table>
<h2>Maturity ladder, by month and tier (open positions)</h2><p>When collateral <em>can</em> leave, not when it will. Month × tier only; no per-height buckets are published.</p>
<table><thead><tr><th>maturity month</th><th>tier</th><th>positions</th><th>of which matured</th><th>DD</th><th>collateral</th></tr></thead><tbody>${mt.map((r) => `<tr><td>${r.maturity_month}</td><td>${r.tier} (${esc(r.tier_label)})</td><td>${r.positions}</td><td>${r.matured_positions}</td><td>${usd(r.cents)}</td><td>${dgb(r.collateral_sats)}</td></tr>`).join("")}</tbody></table>
<h2>Daily flows</h2><p>Burn is a transaction-level quantity (DD consumed minus declared change) and is never allocated to a position. "Extra burn" is burn beyond the mint cents of the positions closed in the same transaction; ${tot.over_mint_events} such events so far.</p>
<table><thead><tr><th>day</th><th>mints</th><th>DD minted</th><th>closes</th><th>collateral released</th><th>burn (type-3)</th><th>burn (no record)</th><th>extra burn</th></tr></thead><tbody>${fl.map((f) => `<tr><td>${f.day}</td><td>${f.mints}</td><td>${usd(f.mint_cents)}</td><td>${f.closes}</td><td>${dgb(f.released_sats)}</td><td>${usd(f.burn_type3_cents)}</td><td>${usd(f.burn_norecord_cents)}</td><td>${usd(f.extra_burn_cents)}</td></tr>`).join("")}</tbody></table>
<h2>Files and provenance</h2><p><a href="latest.json">latest.json</a> · <a href="schema.json">schema.json</a> · <a href="snapshots/${m.snapshot_id}/manifest.json">manifest.json</a> · <a href="snapshots/${m.snapshot_id}/month-tier.json">month-tier.json</a> · <a href="snapshots/${m.snapshot_id}/matured-unredeemed.json">matured-unredeemed.json</a> · <a href="snapshots/${m.snapshot_id}/flows.json">flows.json</a> · <a href="snapshots/${m.snapshot_id}/totals.json">totals.json</a> · <a href="snapshots/${m.snapshot_id}/SHA256SUMS">SHA256SUMS</a></p>
<p>Source: ${esc(m.source)}. DD transactions scanned: ${m.dd_transactions.toLocaleString()}; burn events: ${m.burn_events}; mints with ambiguous collateral: ${m.collateral_ambiguous_mints}. Invariants: ${esc(JSON.stringify(m.invariants))}. Scanner <a href="https://github.com/dgb-tools/dd-position-scanner">dgb-tools/dd-position-scanner</a>. Generated ${esc(m.generated_at)}.</p><pre>${esc(sums)}</pre>
<p><small>Independent community instrument. Not affiliated with the DigiByte Foundation. Corrections: <a href="https://github.com/dgb-tools/dd-position-scanner/issues">issues</a>.</small></p></body></html>`;
fs.mkdirSync(path.join(out, "vaults", "snapshots", m.snapshot_id), { recursive: true }); fs.writeFileSync(path.join(out, "vaults", "index.html"), html);
for (const f of fs.readdirSync(dir)) fs.copyFileSync(path.join(dir, f), path.join(out, "vaults", "snapshots", m.snapshot_id, f));
fs.writeFileSync(path.join(out, "vaults", "latest.json"), JSON.stringify({ snapshot_id: m.snapshot_id, status: m.status, end_height: m.snapshot_end_height, end_hash: m.snapshot_end_hash, totals: tot, matured_unredeemed: { positions: mu.positions, cents: mu.cents, collateral_sats: mu.collateral_sats }, generated_at: m.generated_at }, null, 1));
fs.copyFileSync("schema/position.schema.json", path.join(out, "vaults", "schema.json")); console.error("rendered", path.join(out, "vaults"));
